[package]
name = "thunder"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
v8 = "135.0.0"
blitz-traits = { path = "../blitz-traits" }
blitz-dom = { path = "../blitz-dom" }

html5ever = { workspace = true }
xml5ever = { workspace = true }
url = { workspace = true }

tracing = { workspace = true, optional = true }
tracing-subscriber = { optional = true, version = "*", features = [
    "env-filter",
] }
tokio = { features = ["full"], workspace = true }
reqwest = { workspace = true }
data-url = { workspace = true }

blitz-shell = { path = "../blitz-shell", features = ["menu"] }
blitz-renderer-vello = { path = "../blitz-renderer-vello" }
winit = { workspace = true }
smallvec = "1"

serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
strum = "0.27.1"

[dev-dependencies]

# Features
[features]
default = ["tracing"]
tracing = ["dep:tracing", "dep:tracing-subscriber"]
